name: Pull Request
on:
  push:
    branches-ignore:
       - master
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
       - name: check out the repository
         uses: actions/checkout@v4
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v5
       - name: Post to a Slack channel
         id: slack
         uses: slackapi/slack-github-action@v1.24.0
         with:
            # Slack channel id, channel name, or user id to post message.
            # See also: https://api.slack.com/methods/chat.postMessage#channels
            # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
            channel-id: 'C067BEE3G3H'
            # For posting a simple plain text message
            slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
         env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            #  - name: Make HTTP request
            #    uses: fjogeleit/http-request-action@
            #    id: "make_request"
            #    with:
            #        url: 'http://api.exchangeratesapi.io/v1/latest?access_key=${{ secrets.API_KEY }}&symbols = USD,AUD,CAD,PLN,MXN'
            #        method: GET
            #        customHeaders: '{"content-type": "application/json"}'
       - name: Show Request Response
         run: |
            echo ${{ steps.make_request.response.outputs.response }}
            echo ${{ steps.make_request.outputs.headers }}
       - name: Send mail
         uses: dawidd6/action-send-mail@v3
         with:
            # Specify connection via URL (replaces server_address, server_port, secure,
            # username and password)
            #
            # Format:
            #
            #  * smtp://user:password@server:port
            #  * smtp+starttls://user:password@server:port
            # Required mail server address if not connection_url:
            server_address: smtp.gmail.com
            # Server port, default 25:
            server_port: 465
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
            # Optional (recommended) mail server username:
            username: ${{secrets.MAIL_USERNAME}}
            # Optional (recommended) mail server password:
            password: ${{secrets.MAIL_PASSWORD}}
            # Required mail subject:
            subject: Github Actions job result
            # Required recipients' addresses:
            to: ${{secrets.MAIL_USERNAME}}
            # Required sender full name (address can be skipped):
            from: ${{secrets.MAIL_USERNAME}} # <user@example.com>
            # Optional plain body:
            body: Build job of ${{github.repository}} completed successfully!
            # Optional HTML body read from file:
            # html_body: file://README.html